### ISSUE TITLE
关于最近618 出的即刻 铭帆等mini主机的选择

### ISSUE THREAD

**Issue by yikwongee** [ryan4yin/knowledge#16]
这些我都看到有好多差评，品控都有点问题，老哥能推荐选一下吗？
例如：UM790、GTR7
个人需求：也就玩虚拟机 跑点东西 单双网口都可，最多可能装个win打个联盟

还有就是关于内存和固态的选择

谢谢🙏

**Comment by ryan4yin** [comment]
@yikwongee 我都没怎么注意新机器的情况，毕竟我 homelab 已经搞好了，所以这个需要你自己判断了。

我能给出的结论是，除了坏掉两块固态之外...我买的三台机器用到现在没出过啥毛病。坏掉的固态我也在 homelab 的 README.md 里说过了。

**Comment by yikwongee** [comment]
谢谢🙏
